approvedGitRepositories:
  - "**"

compressionLevel: mixed

enableGlobalCache: false

enableScripts: true

npmMinimalAgeGate: 0

packageExtensions:
  "@sentry/nextjs@*":
    dependencies:
      "@opentelemetry/core": "*"
      "@opentelemetry/sdk-trace-base": "*"

yarnPath: .yarn/releases/yarn-4.17.0.cjs
