sonar.projectKey=BCSDLab_KOIN_WEB_RECODE
sonar.organization=bcsdlab

sonar.sources=src
sonar.exclusions=src/generated/**,**/*.test.ts,**/*.test.tsx,**/__tests__/**

sonar.typescript.tsconfigPath=tsconfig.json
