/**
 * EventSpecification 배열을 받아 TypeScript 로거 훅 코드를 생성하는 모듈.
 * 생성되는 훅은 `useLogger`를 래핑하여 각 이벤트에 대한 타입 안전한 로깅 함수를 제공합니다.
 */

import type { EventSpecification } from './types.js';
import { EXTRA_PARAM_TYPE_MAP } from './types.js';
import { snakeToCamelCase, snakeToPascalCase } from './notion-fetcher.js';

/** extraParams 배열로부터 TypeScript 인라인 객체 타입 문자열을 생성 */
function buildExtraParamsType(extraParams: string[]): string {
  const fields = extraParams.map((key) => `${key}?: ${EXTRA_PARAM_TYPE_MAP[key] ?? 'string'}`).join('; ');
  return `{ ${fields} }`;
}

/**
 * 이벤트 스펙 목록으로부터 TypeScript 로거 훅 코드 문자열을 생성
 *
 * 생성 구조:
 * 1. EVENTS 상수 객체 (각 이벤트의 label, category, value 정의)
 * 2. dynamic value를 가진 이벤트의 타입 정의
 * 3. useLogger를 래핑하는 커스텀 훅 함수
 *
 * @param events - 이벤트 스펙 목록
 * @param team - 팀 식별자 (예: 'CAMPUS')
 * @param hookName - 생성할 훅의 이름 (예: 'Article' → `useArticleLogger`)
 * @returns 완성된 TypeScript 코드 문자열
 */
export function generateLoggerHookCode(events: EventSpecification[], team: string, hookName: string): string {
  const lines: string[] = [];

  lines.push(`// Auto-generated by fetch-logging-spec.ts — ${new Date().toISOString()}`);
  lines.push("import useLogger from 'utils/hooks/analytics/useLogger';");
  lines.push('');
  lines.push(`const TEAM = '${team}';`);
  lines.push('');

  // EVENTS 상수
  lines.push('const EVENTS = {');
  for (const event of events) {
    const key = snakeToCamelCase(event.event_label);
    const categoryPart = event.event_category !== 'click' ? `, event_category: '${event.event_category}'` : '';
    if (event.value_type === 'fixed') {
      lines.push(`  ${key}: { event_label: '${event.event_label}'${categoryPart}, value: '${event.value}' },`);
    } else if (event.values.length) {
      const valuesStr = event.values.map((value) => `'${value}'`).join(', ');
      lines.push(`  ${key}: { event_label: '${event.event_label}'${categoryPart}, values: [${valuesStr}] },`);
    } else {
      lines.push(`  ${key}: { event_label: '${event.event_label}'${categoryPart} },`);
    }
  }
  lines.push('} as const;');
  lines.push('');

  // 타입 정의
  const dynamicEvents = events.filter((event) => event.value_type === 'dynamic');
  for (const event of dynamicEvents) {
    const typeName = `${snakeToPascalCase(event.event_label)}Value`;
    const key = snakeToCamelCase(event.event_label);
    if (event.values.length) {
      lines.push(`export type ${typeName} = (typeof EVENTS.${key}.values)[number];`);
    } else {
      lines.push(`export type ${typeName} = string;`);
    }
  }
  if (dynamicEvents.length) lines.push('');

  // 훅
  lines.push(`export const use${hookName}Logger = () => {`);
  lines.push('  const logger = useLogger();');
  lines.push('');
  events.forEach((event, index) => {
    const key = snakeToCamelCase(event.event_label);
    const fnName = `log${snakeToPascalCase(event.event_label)}`;
    const hasExtra = event.extraParams.length > 0;
    if (index > 0) lines.push('');
    lines.push(`  /** ${event.titles.join(' / ')} */`);

    if (event.value_type === 'fixed' && !hasExtra) {
      lines.push(`  const ${fnName} = () => logger.actionEventClick({ team: TEAM, ...EVENTS.${key} });`);
    } else if (event.value_type === 'fixed' && hasExtra) {
      const paramsType = buildExtraParamsType(event.extraParams);
      lines.push(
        `  const ${fnName} = (params: ${paramsType}) => logger.actionEventClick({ team: TEAM, ...EVENTS.${key}, ...params });`,
      );
    } else if (!hasExtra) {
      const typeName = `${snakeToPascalCase(event.event_label)}Value`;
      lines.push(
        `  const ${fnName} = (value: ${typeName}) => logger.actionEventClick({ team: TEAM, ...EVENTS.${key}, value });`,
      );
    } else {
      const typeName = `${snakeToPascalCase(event.event_label)}Value`;
      const paramsType = buildExtraParamsType(event.extraParams);
      lines.push(
        `  const ${fnName} = (value: ${typeName}, params: ${paramsType}) => logger.actionEventClick({ team: TEAM, ...EVENTS.${key}, value, ...params });`,
      );
    }
  });
  lines.push('');

  // return
  lines.push('  return {');
  for (const event of events) {
    const fnName = `log${snakeToPascalCase(event.event_label)}`;
    lines.push(`    ${fnName},`);
  }
  lines.push('  };');
  lines.push('};');
  lines.push('');

  return lines.join('\n');
}
