type ROUTESParams<T extends string = string> = {
  [key in T]?: string;
};

const ROUTES = {
  Main: () => '/',
  Category: () => '/category',
  NotFound: () => '*',
  Timetable: () => '/timetable',
  TimetableModify: ({ id, type }: ROUTESParams<'id' | 'type'>) =>
    `timetable/modify?id=${id}${type ? `&type=${type}` : ''}`,
  GraduationCalculator: () => '/graduation',
  Course: () => '/course',
  Store: () => '/store',
  BenefitStore: () => '/benefitstore',
  StoreDetail: ({ id }: ROUTESParams<'id'>) => `/store/${id}`,
  BusRoute: () => '/bus/route',
  BusCourseShuttle: () => '/bus/shuttle',
  BusCourseExpress: () => '/bus/express',
  BusCourseCity: () => '/bus/city',
  Club: () => '/clubs',
  ClubDetail: ({ id, hot }: ROUTESParams<'id' | 'hot'>) => `/clubs/${id}?hot=${hot}`,
  NewClub: () => '/clubs/new',
  ClubEdit: ({ id }: ROUTESParams<'id'>) => `/clubs/edit/${id}`,
  NewClubRecruitment: ({ id }: ROUTESParams<'id'>) => `/clubs/recruitment/${id}`,
  ClubRecruitmentEdit: ({ id }: ROUTESParams<'id'>) => `/clubs/recruitment/edit/${id}`,
  NewClubEvent: ({ id }: ROUTESParams<'id'>) => `/clubs/event/${id}`,
  ClubEventEdit: ({ id, eventId }: ROUTESParams<'id' | 'eventId'>) => `/clubs/${id}/event/edit/${eventId}`,
  Cafeteria: ({ date, type }: ROUTESParams<'date' | 'type'> = {}) =>
    `/cafeteria${date ? `?date=${date}${type ? `&type=${type}` : ''}` : ''}`,
  Articles: () => '/articles',
  ArticlesSearch: () => '/articles/search',
  ArticlesDetail: ({ id }: ROUTESParams<'id'>) => `/articles/${id}`,
  LostItems: () => '/lost-item',
  LostItemRedirect: () => '/lost-item',
  LostItemDetail: ({ id }: ROUTESParams<'id'>) => `/lost-item/${id}`,
  LostItemFound: () => '/lost-item/found',
  LostItemLost: () => '/lost-item/lost',
  LostItemChat: () => '/lost-item/chat',
  LostItemEdit: ({ id }: ROUTESParams<'id'>) => `/lost-item/edit/${id}`,
  LostItemReport: ({ id }: ROUTESParams<'id'>) => `/lost-item/report/${id}`,
  Room: () => '/room',
  RoomDetail: ({ id }: ROUTESParams<'id'>) => `/room/${id}`,
  CampusInfo: () => '/campusinfo',
  Department: () => '/department',
  DepartmentCategory: ({ category }: ROUTESParams<'category'>) => `/department/${category}`,
  Auth: () => '/auth',
  Profile: () => '/profile',
  AuthSignup: ({ currentStep }: ROUTESParams<'currentStep'>) => `/auth/signup/${currentStep}`,
  AuthFindPW: ({ step }: ROUTESParams<'step'>) => `/auth/findpw/${step}`,
  // AuthFindPW: () => '/auth/findpw',
  AuthFindID: () => '/auth/findid',
  Phone: () => '/auth/findid/phone',
  Email: () => '/auth/findid/email',
  IDResult: () => '/auth/findid/result',
  AuthModifyInfo: () => '/auth/modifyinfo',
  Review: ({ id }: ROUTESParams<'id'>) => `/store/review/${id}`,
  ReviewEdit: ({ id, reviewId }: ROUTESParams<'id' | 'reviewId'>) => `/store/review/edit/${id}/${reviewId}`,
  ReviewReport: ({ shopid, reviewid }: ROUTESParams<'shopid' | 'reviewid'>) =>
    `/report/review/shopid/${shopid}/reviewid/${reviewid}`,
  Webview: () => '/webview',
  Callvan: () => '/callvan',
  CallvanAdd: () => '/callvan/add',
  CallvanNotifications: () => '/callvan/notifications',
  CallvanChat: ({ id }: ROUTESParams<'id'>) => `/callvan/chat/${id}`,
  CallvanParticipants: ({ postId }: ROUTESParams<'postId'>) => `/callvan/${postId}/participants`,
  CallvanReport: ({ postId, userId }: ROUTESParams<'postId' | 'userId'>) => `/callvan/${postId}/report/${userId}`,
  Team: () => '/team',
  TeamRecruitmentSearch: () => '/team/recruitment/search',
  TeamRecruitmentNew: () => '/team/recruitment/new',
  TeamRecruitmentApply: ({ postId }: ROUTESParams<'postId'>) => `/team/recruitment/${postId}/apply`,
  TeamRecruitmentApplicants: ({ postId }: ROUTESParams<'postId'>) => `/team/recruitment/${postId}/applicants`,
  TeamRecruitmentApplicantDetail: ({ postId, applicantId }: ROUTESParams<'postId' | 'applicantId'>) =>
    `/team/recruitment/${postId}/applicants/${applicantId}`,
  TeamProfile: () => '/team/profile',
  TeamProfileNew: () => '/team/profile/new',
  TeamProfilePosts: () => '/team/profile/posts',
  TeamProfileApplications: () => '/team/profile/applications',
  // TeamDetail은 다른 작업자가 진행 중인 /team/${postId}를 그대로 유지. 그쪽 작업 완료 후 /team/recruitment/${postId}로 함께 정리 예정.
  TeamDetail: ({ postId }: { postId: string }) => `/team/${postId}`,
  TeamNotifications: () => '/team/notifications',
  TeamChat: ({ id }: { id: string }) => `/team/chat/${id}`,
  WebviewCampusInfo: () => '/webview/campusinfo',
  PrivatePolicy: () => '/policy',
  Inquiry: () => 'https://forms.gle/qYw17r2kihThiJvj7',
};

export default ROUTES;
